Rejoin:
  #Can players join again after being kicked by AFKPlus actions
  AllowRejoin: false
  #How many seconds do they need to wait before they can rejoin
  TimeToWait: 60
Reaction:
  #If they can rejoin, how long do they have to prove they are really AFK
  TimeToAction: 5
  #How many seconds must the players wait to rejoin after being allowed to join once
  TimeToWait: 300
#The command to run when the player fails to exit AFK after rejoining
ActionCommand: "tempban {PLAYER} 30m Attempting AFK kick avoidance"

Messages:
  Kick: "&4You cannot rejoin as you were recently kicked for AFKing"
  # Sent to the console when a player tries to join while AllowRejoin is enabled
  # Set to an empty string to disable the message if it is spamming your console
  KickConsole: "{PLAYER} was not allowed to join since they were just kicked for AFKing"
  Rejoin: "You have a few seconds to prove you arent AFK or you will be temp-banned for auto reconnecting"